### ISSUE TITLE
Possible to make this work with phpstorm?

### ISSUE THREAD

**Issue by ghost** [ssut/intellij-apple-silicon-patcher#1]

**Comment by ssut** [comment]
I haven't tested yet but it probably work on all variants of IntelliJ anyway.

**Comment by ghost** [comment]
The script gave no errors, however trying to open phpstorm gives a permission error: https://imgur.com/a/nsb4zcA

**Comment by ssut** [comment]
Could you try:

```bash
$ codesign --remove-signature ./PhpStorm.app/Contents/jbr
$ codesign --remove-signature ./PhpStorm.app
$ sudo xattr -dr com.apple.quarantine ./PhpStorm.app
$ codesign -s - ./PhpStorm.app/Contents/jbr
$ codesign -s - ./PhpStorm.app
```

**Comment by ghost** [comment]
Hey

Unfortunately I'm still getting the same error. I tried doing `open PhpStorm.app` as well, and it produces

`The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2508, NSUnderlyingError=0x15930c790 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x15930d190 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 111}}}}}`

**Comment by ssut** [comment]
Can you please open `PhpStorm.app/Contents/MacOS/idea` directly? or let me know if there's something else.

**Comment by ghost** [comment]
Appreciate the effort! Unfortunately that didn't work either. It produces

```
/Users/stian/Desktop/intellij-apple-silicon-patcher-main/PhpStorm.app/Contents/MacOS/idea ; exit;
stian@stians-mac-mini-m1 ~ % /Users/stian/Desktop/intellij-apple-silicon-patcher-main/PhpStorm.app/Contents/MacOS/idea ; exit;
zsh: killed     
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by ssut** [comment]
Please try:

```
$ rm ./PhpStorm.app/Contents/MacOS/phpstorm
$ mv ./PhpStorm.app/Contents/MacOS/idea ./PhpStorm.app/Contents/MacOS/phpstorm
$ codesign --remove-signature ./PhpStorm.app
$ codesign -s - ./PhpStorm.app
$ sudo xattr -dr com.apple.quarantine ./PhpStorm.app
$ open ./PhpStorm.app
```

<img width="806" alt="Screen Shot 2020-12-09 at 11 31 07 PM" src="https://user-images.githubusercontent.com/2366668/101642678-9da01c80-3a76-11eb-90aa-d7600d588587.png">

**Comment by ghost** [comment]
Oh joy! That sorted it! Thank you so much man

**Comment by LemarinelNet** [comment]
Do you think we could download from somewhere some precompiled binaries ? 
I've tried to build phpStorm, but I couldn't figure exactly how to install all the build tools (xcode command line ??)
Throwing hundreds of one-shot tools in my mac for just one build is a bit overkill to me...

**Comment by ghost** [comment]
> Do you think we could download from somewhere some precompiled binaries ?
> I've tried to build phpStorm, but I couldn't figure exactly how to install all the build tools (xcode command line ??)
> Throwing hundreds of one-shot tools in my mac for just one build is a bit overkill to me...

Install xcode from the app store. Then install cmake via homebrew and you should be good

**Comment by ssut** [comment]
> Do you think we could download from somewhere some precompiled binaries ?
> I've tried to build phpStorm, but I couldn't figure exactly how to install all the build tools (xcode command line ??)
> Throwing hundreds of one-shot tools in my mac for just one build is a bit overkill to me...

I think it's not a good idea to redistribute the IDE that is owned by JetBrains. Please try with above steps.
